### ISSUE TITLE
After signup, app showing only  load progress indicator und don't go in the home page..

### ISSUE THREAD

**Issue by ana675** [Ronak99/Skype-Clone#16]

**Comment by takiuddin93** [comment]
Does it throw an error? I had the same issue. Then I figured I didn't redirect to dashboard/homepage after authentication is success.

I still have the same issue at times, but that due to bad internet or connection dropping for a second during authentication.

Can you provide more details?

**Comment by ana675** [comment]
All firebase related settings are set, and also the sha1 has been added but for some reason don't go in the home page. 

Restarted application in 3,097ms.
W/Firestore( 7819): (19.0.0) [Firestore]: Listen for Query(users/WBh1syKODmSr32HqWEITHlFMtD72) failed: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}
E/flutter ( 7819): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Error performing get, PERMISSION_DENIED: Missing or insufficient permissions., null)
E/flutter ( 7819): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 7819): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 7819): <asynchronous suspension>
E/flutter ( 7819): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 7819): #3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:356:48)
E/flutter ( 7819): #4      DocumentReference.get (package:cloud_firestore/src/document_reference.dart:84:33)
E/flutter ( 7819): #5      AuthMethods.getUserDetails (package:skype_clone/resources/auth_methods.dart:32:57)
E/flutter ( 7819): <asynchronous suspension>
E/flutter ( 7819): #6      UserProvider.refreshUser (package:skype_clone/provider/user_provider.dart:12:36)
E/flutter ( 7819): #7      _HomeScreenState.initState.<anonymous closure> (package:skype_clone/screens/home_screen.dart:31:26)
E/flutter ( 7819): #8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
E/flutter ( 7819): #9      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1060:9)
E/flutter ( 7819): #10     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
E/flutter ( 7819): #11     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 7819): #12     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 7819): #13     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 7819): #14     _invoke (dart:ui/hooks.dart:261:10)
E/flutter ( 7819): #15     _drawFrame (dart:ui/hooks.dart:219:3)

**Comment by ana675** [comment]
Error is fixed after allow all rules in the firebase settings in the real time database and cloud firestore...

**Comment by ana675** [comment]
But one more error I can't run the app on the iOS devices..
